name: Tests

on:
  push: 
    branches: [dev]

jobs:

  ui-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: mv schedule-data-service/database/template_nodehill_schedule.db schedule-data-service/database/nodehill_schedule.db
    - run: cd admin/ && npm ci && npm run build
    - run: cd schedule-data-service/ && npm ci
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        start: npm run dev
  
  api-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: mv schedule-data-service/database/template_nodehill_schedule.db schedule-data-service/database/nodehill_schedule.db
    - run: cd admin/ && npm ci && npm run build
    - run: cd schedule-data-service/ && npm ci
    - run: npm install -g pm2
    - run: pm2 start "npm run dev"
    - run: npm install -g newman
    - run: newman run test-api-postman/admin-tests.postman_collection.json
    - run: newman run test-api-postman/user-tests.postman_collection.json
    - run: newman run test-api-postman/visitor-test.postman_collection.json

  publish-dev:
    needs: [ui-tests, api-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Pull origin
        run: ssh dev 'cd schedule-planner/ && git fetch && git pull origin dev && npm i'
      - name: Build
        run: ssh dev 'cd schedule-planner/ && cd admin && npm i && npm run build'
      - name: Install
        run: ssh dev 'cd schedule-planner/ && cd schedule-data-service && npm i'

      - name: Reset database
        run: ssh dev 'cd schedule-planner/ && cp schedule-data-service/database/template_nodehill_schedule.db schedule-data-service/database/nodehill_schedule.db'

      - name: Restart app
        run: ssh dev 'pm2 restart schedule-planner'